### ISSUE TITLE
GPIO PIN: wrong pin spacing

### ISSUE THREAD

**Issue by linuxlurak** [anuditnagar/fritzing#1]
Thank you for the work with this fritzing part!

I think you took the wrong pin spacing for the gpio pins. Perhaps 2mm? The raspberry pi zero actually has a standard 2.54mm resp. 0.1inc pin spacing.

Another suggestion/wish: Could you create a pcb shape for the pi zero? would be great! i tried to create one but after a lot of trial and error i resignated...

**Comment by anudit** [comment]
Thanks for the suggestion. I am working towards creating parts for the
updated versions of the Pi and Pi Zero with updated PCB and schematics.

**Comment by gbaman** [comment]
Any updates on this? Have been badly bitten by it now and would be keen others weren't in the future - https://github.com/fritzing/fritzing-parts/issues/107

**Comment by linuxlurak** [comment]
I switched to diptrace. It's the way to go. No offense!

**Comment by anudit** [comment]
The updated part has been commited to the repository.
